print('What to you get when you cross a snowman and a vampire?')
input()
print(' A Frostbite!')
print()
print("What do denntists call a astronaut\'s cavity?")
input()
print(' A black hole!')
print()
print("Knock, Knock.")
input()
print(" Who's there?")
input()
print('interupting cow.')
input()
print('Interupting cow wh', end='')
print('-Moo!!!')
